In [35]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

##1.1 Creating a Vector
Problem
You need to create a vector.

In [36]:
# Problem: You need to create a vector(One-Dimentional array).

# Create a vector as a row
vector_1 = np.array([1, 2, 3, 4, 5])


# Create a vector as a column
vector_2 = np.array([[1],
                     [2],
                     [3]])

print('Vector 1: ', vector_1)
print('Vector 2: ', vector_2)

Vector 1:  [1 2 3 4 5]
Vector 2:  [[1]
 [2]
 [3]]


##Discussion 1.1
NumPy’s main data structure is the multidimensional array. To create a vector, we
simply create a one-dimensional array. Just like vectors, these arrays can be repre‐
sented horizontally (i.e., rows) or vertically (i.e., columns).

##1.2 Creating a Matrix
Problem
You need to create a matrix.

In [37]:
matrix_1 = np.mat([[1, 2, 3, 4, 5],[6, 7, 8 ,9 ,10]])
matrix_1

matrix([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])

## Discussion 1.2
To create a matrix we can use a NumPy two-dimensional array. In our solution, the
matrix contains three rows and two columns (a column of 1s and a column of 2s).

##1.3 Creating a Sparse Matrix
Problem
Given data with very few nonzero values, you want to efficiently represent it.

In [38]:
from scipy import sparse
# Create a matrix
matrix = np.array([[0, 0],
                   [0, 1],
                   [3, 0]])
# Create compressed sparse row (CSR) matrix
matrix_sparse = sparse.csr_matrix(matrix)
print(matrix_sparse)

  (1, 1)	1
  (2, 0)	3


##1.4 Selecting Elements
Problem
You need to select one or more elements in a vector or matrix.

In [39]:
# Create row vector
vector = np.array([1, 2, 3, 4, 5, 6])


# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])


# Select third element of vector
print(vector[2])


# Select second row, second 3rd Column
matrix[1,2]

3


6

##Discussion
Like most things in Python, NumPy arrays are zero-indexed, meaning that the index
of the first element is 0, not 1. With that caveat, NumPy offers a wide variety of methods for selecting (i.e., indexing and slicing) elements or groups of elements in arrays:

In [40]:
vector = np.array([1, 2, 3, 4, 5, 6])

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])



# Select all elements of a vector
# vector/vector[:]


# Select everything up to and including the third element
# vector[:3]


# Select everything after the third element
# vector[3:]


# Select the last element
# vector[-1]


# Select the first two rows and all columns of a matrix
matrix[:2, :]


# Select all rows and the second column
matrix[:, 1:2]

array([[2],
       [5],
       [8]])

##1.5 Describing a Matrix
Problem:
* You want to describe the shape, size, and dimensions of the matrix.

👉 *Use shape, size, and ndim:*

In [41]:
matrix = np.array([[1,2,3,4,5],[5,6,7,8,9]])
print(matrix.shape)
print(matrix.ndim)
print(matrix.size)

(2, 5)
2
10


##Discussion
This might seem basic (and it is); however, time and again it will be valuable to check
the shape and size of an array both for further calculations and simply as a gut check
after some operation.

##1.6 Applying Operations to Elements
**Problem:**
* You want to apply some function to multiple elements in an array

In [42]:
from operator import add
# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Create function that adds 100 to something
def add_100_to_something(something):
  return something + 100

# Create function that adds 100 to something
# add_100_to_something(matrix[:, 1:2])
add_100 = lambda i: i + 100


# Create vectorized function
vectorized_add_100 = np.vectorize(add_100)
# Apply function to all elements in matrix
vectorized_add_100(matrix)

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

##Discussion
* NumPy’s vectorize class converts a function into a function that can apply to all elements in an array or slice of an array. 
* It’s worth noting that vectorize is essentially a for loop over the elements and does not increase performance. 
* Furthermore, NumPy arrays allow us to perform operations between arrays even if their dimensions are not the same (a process called broadcasting.
* For example, we can create a much simpler
version of our solution using broadcasting:

In [43]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

matrix += 100
matrix

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

##1.7 Finding the Maximum and Minimum Values in a np array
**Problem:** 
* You need to find the maximum or minimum value in an array.

In [44]:
array_1 = np.array([1,2,3,4,5])
list_1 = [1,2,3,4,5]


# Finding the maximum and minimum values in a numpy array
maximum_of_array = np.max(array_1)
minimum_of_array = np.min(array_1)

print("Maximum num in array: ", maximum_of_array)
print("Minimum num in array: ", minimum_of_array)

# Finding the maximum and minimum values in a list without using function
min_num = list_1[0]
max_num = min_num

for num in list_1:
  if num<min_num:
    min_num = num
  
  elif num > max_num:
    max_num = num

print("Minimum number in list: ", min_num)
print("Maximum number in list: ",max_num)


Maximum num in array:  5
Minimum num in array:  1
Minimum number in list:  1
Maximum number in list:  5


##1.7-B Finding the Maximum and Minimum Values in a matrix
**Problem:** 
* You need to find the maximum or minimum value in an matrix.

In [45]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# maximum value in each column
maximum_in_columns = np.max(matrix, axis=1)
print("Maximum numbers in each column: ", maximum_in_columns)


# maximum value in each row
maximum_in_rows = np.max(matrix, axis=0)
print("Maximum numbers in each row: ", maximum_in_rows)

Maximum numbers in each column:  [3 6 9]
Maximum numbers in each row:  [7 8 9]


##Discussion
Often we want to know the maximum and minimum value in an array or subset of an array. This can be accomplished with the max and min methods. Using the axis parameter we can also apply the operation along a certain axis:
* Find maximum element in each column

```np.max(matrix, axis=0)```

output : array([7, 8, 9])

*  Find maximum element in each row

```np.max(matrix, axis=1)```

output : array([3, 6, 9])

##1.8 Calculating the Average, Variance, and Standard Deviation
**Problem :**
* You want to calculate some descriptive statistics about an array.

In [46]:
# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])


# this will return the average of the matrix
average = np.mean(matrix)


# this will return the varience of the matrix
variance = np.var(matrix)


# this will return the Standard deviation of matrix
s_daviation = np.std(matrix)


# Print them all
print(f"Average: {average.round(3)}")
print(f"Variance: {variance.round(2)}")
print(f"Standard deviation: {variance.round(2)}")

Average: 5.0
Variance: 6.67
Standard deviation: 6.67


##Discussion
Just like with max and min, we can easily get descriptive statistics about the whole
matrix or do calculations along a single axis:
# Find the mean value in each column
```np.mean(matrix, axis=0)```


array  ( [ 4., 5., 6.] )


##1.9 Reshaping Arrays
**Problem:**

You want to change the shape (number of rows and columns) of an array without changing the element values.

In [47]:
# Unsing reshape attribute
matrix = np.array([[1,2,3],
                   [4,5,6]])



new_matrix = matrix.reshape(3, 2)

print(f"orignal matrix: \n{matrix}")
print(f"size of orignal matrix: \n{matrix.size}")
print()
print(f"new matrix: \n{new_matrix}")
print(f"size of new matrix: \n{new_matrix.size}")


orignal matrix: 
[[1 2 3]
 [4 5 6]]
size of orignal matrix: 
6

new matrix: 
[[1 2]
 [3 4]
 [5 6]]
size of new matrix: 
6


##Discussion
reshape allows us to restructure an array so that we maintain the same data but it is
organized as a different number of rows and columns. The only requirement is that
the shape of the original and new matrix contain the same number of elements (i.e., the same size). 

We can see the size of a matrix using size:

```matrix.size```

__output: 12__

*One useful argument in reshape is -1, which effectively means “as many as needed,”*

so __reshape ( -1,  1 )__ means one row and as many columns as needed:

```matrix.reshape(1, -1)```

output: array( [ [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12 ] ] )

Finally, if we provide one integer, reshape will return a 1D array of that length:

```matrix.reshape(12)```

output: array([ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

In [48]:
matrix = np.array([[1,2,3],
                   [4,5,6]])


# provide one integer, reshape will return a 1D array of that length:
print("Returning 1D array: \n", matrix.reshape(6))
print()


# means one column and as many rows as needed
print("one row and as many rows as needed: \n", matrix.reshape(-1, 1))
print()


# means one row and as many columns as needed
print("one row and as many columns as needed: \n", matrix.reshape(1, -1))


Returning 1D array: 
 [1 2 3 4 5 6]

one row and as many rows as needed: 
 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]]

one row and as many columns as needed: 
 [[1 2 3 4 5 6]]


## 1.10 Transposing a Vector or Matrix
**Problem :**

* You need to transpose a vector or matrix.

In [49]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

transposed_matrix = matrix.T
transposed_matrix

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

## Discussion
Transposing is a common operation in linear algebra where the column and row indices of each element are swapped. One nuanced point that is typically overlooked outside of a linear algebra class is that, technically, a vector cannot be transposed
because it is just a collection of values:

__Transpose vector :__

```np.array([1, 2, 3, 4, 5, 6]).T```

```array([1, 2, 3, 4, 5, 6])```

However, it is common to refer to transposing a vector as converting a row vector to
a column vector (notice the second pair of brackets) or vice versa:
# Tranpose row vector
``` np.array([[1, 2, 3, 4, 5, 6]]).T```

__output :__

array([[1],

       [2],
       [3],
       [4],
       [5],
       [6]])

## 1.11 Flattening a Matrix
__Problem :__

* You need to transform a matrix into a one-dimensional array.

In [50]:
# using flatten() method
matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

flattened_matrix = matrix.flatten()
flattened_matrix

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

## Discussion
flatten is a simple method to transform a matrix into a one-dimensional array.
Alternatively, we can use reshape to create a row vector:
matrix.reshape(1, -1)
```array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])```

## 1.12 Finding the Rank of a Matrix
__Problem :__
* You need to know the rank of a matrix.

In [51]:
# using matrix_rank method
matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])


# Return matrix rank
np.linalg.matrix_rank(matrix)

2

## 1.13 Calculating the Determinant
__Problem :__
* You need to know the determinant of a matrix.

In [52]:
# Create matrix
matrix = np.array([[1, 2, 3],
                   [2, 4, 6],
                   [3, 8, 9]])

# Return determinant of matrix
np.linalg.det(matrix)

0.0

## 1.14 Getting the Diagonal of a Matrix
__Problem :__
* You need to get the diagonal elements of a matrix.


In [53]:
# Create matrix
matrix = np.array([[1, 2, 3],
                   [2, 4, 6],
                   [3, 8, 9]])

# returns the diagonal elements of the matrix
matrix.diagonal()

array([1, 4, 9])

## Discussion
NumPy makes getting the diagonal elements of a matrix easy with diagonal. It is also possible to get a diagonal off from the main diagonal by using the offset parameter:

* #Returns diagonal one above the main diagonal

```matrix.diagonal(offset=1)```

output: array ( [ 2 , 6 ] )

* #Return diagonal one below the main diagonal

```matrix.diagonal(offset=-1)```

output: array ( [ 2 , 8 ] )

# 1.15 Calculating Dot Products
__Problem :__
* You need to calculate the dot product of two vectors.

In [54]:
# Create two vectors
vector_a = np.array([1,2,3])
vector_b = np.array([4,5,6])

# calculting the dot product of two vectors
np.dot(vector_a, vector_b)

32

## Discussion
The dot product of two vectors, a and b, is defined as:

$\mathbf{a} \cdot \mathbf{b} = \sum_{i=1}^n a_i b_i$.

where ai is the ith element of vector a. We can use NumPy’s dot class to calculate the
dot product. Alternatively, in Python 3.5+ we can use the new @ operator:
# Calculate dot product
vector_a @ vector_b

32

## 1.16 Adding and Subtracting Matrices
__Problem :__
* You want to add or subtract two matrices.

In [55]:

# Create matrix
matrix_a = np.array([[1, 1, 1],
                     [1, 1, 1],
                     [1, 1, 2]])
# Create matrix
matrix_b = np.array([[1, 3, 1],
                     [1, 3, 1],
                     [1, 3, 8]])

# adding two matrices
print("Adding two matrix: \n", np.add(matrix_a, matrix_b))

print()

# subtracting b matrix from a
print("Subtracting matrix a from b: \n",np.subtract(matrix_a, matrix_b))

Adding two matrix: 
 [[ 2  4  2]
 [ 2  4  2]
 [ 2  4 10]]

Subtracting matrix a from b: 
 [[ 0 -2  0]
 [ 0 -2  0]
 [ 0 -2 -6]]


## Discussion
Alternatively, we can simply use the + and - operators:
* Add two matrices

  ```matrix_a + matrix_b```

## 1.17 Multiplying Matrices
__Problem :__
* You want to multiply two matrices

In [56]:
# Create matrix
matrix_a = np.array([[1, 1],
                     [1, 2]])

# Create matrix
matrix_b = np.array([[1, 3],
                     [1, 2]])

# Multiply two matrices
np.dot(matrix_a, matrix_b)

array([[2, 5],
       [3, 7]])

## Discussion
Alternatively, in Python 3.5+ we can use the @ operator:

* Multiply two matrices

```matrix_a @ matrix_b```

If we want to do element-wise multiplication, we can use the * operator:
* Multiply two matrices element-wise

```matrix_a * matrix_b```

## 1.18 Inverting a Matrix
__Problem :__

* You want to calculate the inverse of a square matrix.

In [57]:
# Load library
import numpy as np
# Create matrix
matrix = np.array([[1, 4],
                   [2, 5]])
# Calculate inverse of matrix
np.linalg.inv(matrix)

array([[-1.66666667,  1.33333333],
       [ 0.66666667, -0.33333333]])

Discussion
The inverse of a square matrix, A, is a second matrix A–1, such that:
$$ {AA}^{-1} = I$$
where I is the identity matrix. In NumPy we can use linalg.inv to calculate A–1 if it
exists. 

To see this in action, we can multiply a matrix by its inverse and the result is
the identity matrix:
# Multiply matrix and its inverse
```matrix @ np.linalg.inv(matrix)```

## 1.19 Generating Random Values
__Problem :__

* You want to generate pseudorandom values.

In [58]:
# Set seed
np.random.seed(0)


# Generate three random floats between 0.0 and 1.0
np.random.random(3)

array([0.5488135 , 0.71518937, 0.60276338])

## Discussion
NumPy offers a wide variety of means to generate random numbers, many more than can be covered here. In our solution we generated floats; however, it is also common to generate integers