In [ ]:
#### Importing NumPy
import numpy as np

In [ ]:
#### First example on 1D-array
a = np.array([1, 2, 3, 4, 5])
a.dtype
print(a)

[1 2 3 4 5]


In [ ]:
#### Another way to initialize a NumPy array
b = np.arange(1, 6)
b

array([1, 2, 3, 4, 5])

In [ ]:
#### Zero dimnsional array
zero_d = np.array(100)
zero_d

array(100)

In [ ]:
#### One dimensional array
one_d = np.array([1, 2, 3, 4, 5])
one_d

array([1, 2, 3, 4, 5])

In [ ]:
#### Two dimensional array
two_d = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]])
two_d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
#### Three dimensional array
three_d = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]])
three_d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [ ]:
#### High dimension arrays
## ndmin

arr3 = np.array([1, 2, 3, 4, 5])
print(arr3.ndim)


1


In [ ]:
#### Operations on array elements
print(f"Addition of first and second elements of an array: {arr3[0]+arr3[1]}")
print(f"Squaring the elements of an array: {arr3 ** 2}")

Addition of first and second elements of an array: 3
Squaring the elements of an array: [ 1  4  9 16 25]


### Accessing the rows and columns in 2D-array


In [ ]:
#### Accessing the rows and columns in 2D-array

arr4 = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]])
print(arr4)
print(f"The element at 2nd row and 3rd column is: {arr4[1, 2]}")
print(f"The element at the last row and last column of array is: {arr4[-1, -1]}")

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
The element at 2nd row and 3rd column is: 8
The element at the last row and last column of array is: 10


## Slicing in NumPy Arrays

In [ ]:
#### Accessing the odd elements in an array
print(arr4[0][0:5:2])

[1 3 5]


## 2-D Array Slicing (1)


In [ ]:
arr5 = np.array([[10, 11, 12, 13, 14], [15,16,17,18,19]])
print(arr5[0:2, 2:4])

# “arr[0:2, 2:4]” returns the elements from row0 to row (2-1), and from col2 to col (4-1)

[[12 13]
 [17 18]]


## 2-D Array Slicing (2)

In [ ]:
arr6 = np.array([[10, 11, 12, 13, 14], [15,16,17,18,19]])

print(arr6[0, 2:5])
print(arr6[1, 2:5])

[12 13 14]
[17 18 19]


## 2-D Array Slicing (3)
The 3rd syntax to slice a 2-d array is:

*   myArray[ row1: row2, col ]



In [ ]:
arr6 = np.array([[10, 11, 12, 13, 14], [15,16,17,18,19]])

print(arr6[0:2, 2])
print(arr6[0:1, 1])


[12 17]
[11]


## **_NumPy Data Type_**

In [ ]:
arr7 = np.array([1, 2, 3, 4, 5], dtype='S')
arr7

array([b'1', b'2', b'3', b'4', b'5'], dtype='|S1')

In [ ]:
## Copy the array
arr7 = np.array([1, 2, 3, 4, 5])

arr8 = arr7.copy()
print(arr7)
print(arr8)

[1 2 3 4 5]
[1 2 3 4 5]


In [ ]:
## View the array
arr9 = np.array([21, 22, 23, 24, 25])
arr10 = arr9.view()

print(f"Array 9 : {arr9}")
print(f"Array 10: {arr10}")
print()
arr9[3] = 244
print()
print(f"Array 9 : {arr9}")
print(f"Array 10: {arr10}")
print()
print(arr10.base) ### this shos that viewd array is corelated to orignal array

## Changing in the orignal array affects the view array but it does not affect the copied array

Array 9 : [21 22 23 24 25]
Array 10: [21 22 23 24 25]


Array 9 : [ 21  22  23 244  25]
Array 10: [ 21  22  23 244  25]

[ 21  22  23 244  25]


## **_Reshape 1D array to 2D array_**

In [ ]:
oned_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15])
print(oned_array)

new_array = oned_array.reshape(3, 5)
print(new_array)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


## **_Reshape 2D array to 3D array_**

In [ ]:
oned_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16])
new_3d_array = oned_array.reshape(2, 4, 2)
new_3d_array

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16]]])

## **_Iterating 1-d Array_**

In [ ]:
array11 = np.array([10, 11, 12, 13, 14, 15])
new_arr = []
for i in array11:
  new_arr.append(i)
  print(i)
print()
print(new_arr)

10
11
12
13
14
15

[10, 11, 12, 13, 14, 15]


## **_Iterating 2-d Array_**
The syntax to iterate through all elements in a 2-d array is:
* [ for num in myArray ]

In [ ]:
td_arr = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]])
emp = []
for nums in td_arr:
  emp.append(nums)
  # print(nums)

print(emp)

[array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10])]


## **_Iterating 3D Array_**

In [ ]:
myArr=np.array([[[10,11,12],[13,14,15]],[[16,17,18],[19,20,21]]])

for nums in myArr:
  print(nums)

[[10 11 12]
 [13 14 15]]
[[16 17 18]
 [19 20 21]]


## **_Axis, a Big Issue_**
When concatenating two arrays, we will use a parameter “axis”.
* axis = 0   # joins two arrays vertically
* axis = 1   # joins two arrays horizontally

In [ ]:
arr12 = np.array([[1, 2],[3, 4]])
arr13 = np.array([[5, 6],[7, 8]])

print(arr12, arr13)

[[1 2]
 [3 4]] [[5 6]
 [7 8]]


## **_Sort String Array_**

In [ ]:
my_arr = np.array([5, 6 ,1, 3, 2, 9])

np.sort(my_arr)

array([1, 2, 3, 5, 6, 9])

In [ ]:
myArr = np.array([ 10, 55, 21, 62, 29, 75, 36, 98])
even = np.where(myArr % 2 == 0)
print(myArr[even])
print(even)

[10 62 36 98]
(array([0, 3, 6, 7]),)


## **_Arthematic operations on Arrays_**

In [ ]:
a = np.array([[1,2,30],[10,15,4]])  
b = np.array([[1,2,3],[12, 19, 29]]) 

print(f"Addition of a and b:\n {a + b}")
print(f"Subtraction of a and b:\n {a - b}")
print(f"Multiplication of a and b:\n {a * b}")
print(f"Division of a and b:\n {a / b}")


Addition of a and b:
 [[ 2  4 33]
 [22 34 33]]
Subtraction of a and b:
 [[  0   0  27]
 [ -2  -4 -25]]
Multiplication of a and b:
 [[  1   4  90]
 [120 285 116]]
Division of a and b:
 [[ 1.          1.         10.        ]
 [ 0.83333333  0.78947368  0.13793103]]


In [ ]:
#### Numpy zeros

zero_arr = np.zeros((4, 4, 4),dtype=int)
zero_arr

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [ ]:
### Ones array

ones_arr = np.ones((2,3,3), dtype=np.int64)
ones_arr

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [ ]:
### Numpy array from existing data

l = [1, 2, 3, 4, 5]

arr = np.asarray(l)

arr
print(type(l))
print(type(arr))

<class 'list'>
<class 'numpy.ndarray'>


In [ ]:
#### np.arange()

my_arr1 = np.arange(10, 20, 2)

my_arr1

array([10, 12, 14, 16, 18])

In [ ]:
#### Linspace

my_arr1 = np.linspace(10, 20, 10)

my_arr1

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [ ]:
### Broadcasting

# Smaller array is operating the operation on larger array completely

a = np.array([[1,2,3,4],[2,4,5,6],[10,20,39,3]])  
b = np.array([2,4,6,8])  
print("\nprinting array a..")  
print(a)  
print("\nprinting array b..")  
print(b)  
print("\nAdding arrays a and b ..")  
c = a + b;  
print(c)


printing array a..
[[ 1  2  3  4]
 [ 2  4  5  6]
 [10 20 39  3]]

printing array b..
[2 4 6 8]

Adding arrays a and b ..
[[ 3  6  9 12]
 [ 4  8 11 14]
 [12 24 45 11]]


In [ ]:
a = np.array([[1,2,3,4],[2,4,5,6],[10,20,39,3]])  
  
print("\nPrinting the array:\n")  
  
print(a)  
  
print("\nPrinting the transpose of the array:\n")  
at = a.T  
  
print(at)  
  
print("\nIterating over the transposed array\n")  
  
for x in np.nditer(at):  
    print(x, end= ' ')  
  
print("\nSorting the transposed array in C-style:\n")  
  
c = at.copy(order = 'C')  
  
print(c)  
  
print("\nIterating over the C-style array:\n")  
for x in np.nditer(c):  
    print(x,end=' ')  
      
  
d = at.copy(order = 'F')  
  
print(d)  
print("Iterating over the F-style array:\n")  
for x in np.nditer(d):  
    print(x,end=' ')


Printing the array:

[[ 1  2  3  4]
 [ 2  4  5  6]
 [10 20 39  3]]

Printing the transpose of the array:

[[ 1  2 10]
 [ 2  4 20]
 [ 3  5 39]
 [ 4  6  3]]

Iterating over the transposed array

1 2 3 4 2 4 5 6 10 20 39 3 
Sorting the transposed array in C-style:

[[ 1  2 10]
 [ 2  4 20]
 [ 3  5 39]
 [ 4  6  3]]

Iterating over the C-style array:

1 2 10 2 4 20 3 5 39 4 6 3 [[ 1  2 10]
 [ 2  4 20]
 [ 3  5 39]
 [ 4  6  3]]
Iterating over the F-style array:

1 2 3 4 2 4 5 6 10 20 39 3 

In [ ]:
a = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]])

b = at.copy(order = 'C')
b

array([[ 1,  2, 10],
       [ 2,  4, 20],
       [ 3,  5, 39],
       [ 4,  6,  3]])

In [ ]:
orignal_array = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]])

print(orignal_array)
print()
for nums in orignal_array:
  nums *= 3
  print(nums)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

[ 3  6  9 12 15]
[18 21 24 27 30]


## **_NumPy Mathematical Functions_**

In [ ]:
import numpy as np  
arr = np.array([0, 30, 60, 90, 120, 150, 180])  
print("\nThe sin value of the angles",end = " ")  
print(np.sin(arr * np.pi/180))  
print("\nThe cosine value of the angles",end = " ")  
print(np.cos(arr * np.pi/180))  
print("\nThe tangent value of the angles",end = " ")  
print(np.tan(arr * np.pi/180))


The sin value of the angles [0.00000000e+00 5.00000000e-01 8.66025404e-01 1.00000000e+00
 8.66025404e-01 5.00000000e-01 1.22464680e-16]

The cosine value of the angles [ 1.00000000e+00  8.66025404e-01  5.00000000e-01  6.12323400e-17
 -5.00000000e-01 -8.66025404e-01 -1.00000000e+00]

The tangent value of the angles [ 0.00000000e+00  5.77350269e-01  1.73205081e+00  1.63312394e+16
 -1.73205081e+00 -5.77350269e-01 -1.22464680e-16]


In [ ]:
## Maximum value in a array

arra1 = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10],[1,1,0,1,1]])

maximum = np.max(arra1)
minimum = np.min(arra1)

print(maximum)
print(minimum)

10
0


## **_Calculating median, mean, and average of array items_**

In [ ]:
arra2 = np.array([[1, 2, 3],[4, 5, 6]])
print(arra2.mean())
print(np.median(arra2, 0))

3.5
[2.5 3.5 4.5]


In [ ]:
### Sorting a numpy array along columns
a = np.array([[10,2,3],[4,5,6],[7,8,9]])

print(np.sort(a))


[[ 2  3 10]
 [ 4  5  6]
 [ 7  8  9]]


In [ ]:
### Sorting a numpy array along rows
a = np.array([[10,2,3],[4,5,6],[7,8,9]])
print(np.sort(a, 0))

[[ 4  2  3]
 [ 7  5  6]
 [10  8  9]]


In [ ]:
## Sorting a numpy array by name

a = np.array(['Ayaz', 'Zahoor', 'Aaqib', 'Muqeet'])

print(np.sort(a))

['Aaqib' 'Ayaz' 'Muqeet' 'Zahoor']


## **_NumPy Linear Algebra_**

In [ ]:
a = np.array([[1, 2, 3], 
              [4, 5, 6],
              [10, 11, 12]])
b = np.array([[7, 8, 9],
              [10, 11, 12],
              [4, 5, 6]])

dot_product = a.dot(b)
v_dot = np.vdot(a, b)
print(dot_product)
print(v_dot)

[[ 39  45  51]
 [102 117 132]
 [228 261 294]]
384


In [ ]:
### Inner function
a = np.array([1,2,3,4,5,6])  
b = np.array([23,23,12,2,1,2])  
inner = np.inner(a,b)  
print(inner)  

130


In [ ]:
### Determinant of two numpy arrays

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [8, 9]])

print(np.linalg.det(a))
print(np.linalg.det(b))

-2.0000000000000004
-2.9999999999999996


In [ ]:
### Multiplicative inverse of a numpy array

a = np.array([[1, 2],
              [3, 4]])

b = np.array([[5, 6],
              [8, 9]])

np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [ ]:
### Multiplication of two matrices

a = np.array([[0, 1, 2],
              [3, 4, 5]])

b = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print(a.shape)
print(b.shape)
np.matmul(a, b)

(2, 3)
(3, 3)


array([[18, 21, 24],
       [54, 66, 78]])